name: Generate a PR to bump openstack-k8s-operators dependencies

on:
  workflow_call:
    inputs:
      operator_name:
        required: true
        type: string
      branch_name:
        default: 'main'
        type: string
      custom_image:
        default: 'quay.io/openstack-k8s-operators/openstack-k8s-operators-ci-build-tools:latest'
        type: string
    secrets:
      FORCE_BUMP_PULL_REQUEST_PAT:
        required: false

jobs:

  force-bump-pr:
    name: Generate a pull request update to the latest openstack-k8s-operators dependencies for the selected operator
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.custom_image }}
      options: --user root
    env:
      CUSTOM_TOOLS_PATH: /tmp/workspace/bin

    steps:
    - name: Checkout repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        ref: ${{ inputs.branch_name }}

    - name: Git config
      run: |
        # Fix git ownership issue in container
        git config --global --add safe.directory $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        git config user.name "openstack-k8s-operators-ci"
        git config user.email "openstack-k8s-operators-ci@github.com"

    - name: run make force-bump, tidy, manifests, generate
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PATH: ${{ env.CUSTOM_TOOLS_PATH }}:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        LOCALBIN: ${{ env.CUSTOM_TOOLS_PATH }}
        GOTOOLCHAIN: local
      run: |
        cd $GITHUB_WORKSPACE
        go work init
        make gowork
        BRANCH='${{ inputs.branch_name }}' make force-bump
        go work sync
        make tidy
        make manifests generate

    - name: run make bindata
      if: inputs.operator_name == 'openstack'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PATH: ${{ env.CUSTOM_TOOLS_PATH }}:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        LOCALBIN: ${{ env.CUSTOM_TOOLS_PATH }}
        GOTOOLCHAIN: local
      run: |
        cd $GITHUB_WORKSPACE
        make bindata

    - name: Detect if there are local git changes and set a variable
      id: git_diff
      run: |
        cd $GITHUB_WORKSPACE
        if git diff --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
        else
            echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Set token
      id: token
      run: |
        if [ -z "${{ secrets.FORCE_BUMP_PULL_REQUEST_PAT }}" ]; then
          echo "token=${{ secrets.GITHUB_TOKEN }}" >> "$GITHUB_OUTPUT"
        else
          echo "token=${{ secrets.FORCE_BUMP_PULL_REQUEST_PAT }}" >> "$GITHUB_OUTPUT"
        fi

    - name: Create Pull Request
      if: steps.git_diff.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
      with:
        token: ${{ steps.token.outputs.token }}
        title: "openstack-k8s-operators dependency bump branch: ${{ inputs.branch_name }}"
        branch: "openstack-dependency-bump/${{ inputs.branch_name }}"
        commit-message: "Update openstack-k8s-operators (${{ inputs.branch_name }})"
        committer: openstack-k8s-operators-ci <openstack-k8s-operators-ci@github.com>
        author: openstack-k8s-operators-ci <openstack-k8s-operators-ci@github.com>
        labels: ok-to-test
